apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nvidia-driver-runtime.fullname" . }}
  labels:
    {{- include "nvidia-driver-runtime.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "nvidia-driver-runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nvidia-driver-runtime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
      hostPID: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:  
        - name: nvidia-container-toolkit
          args:
          - /bin/entrypoint.sh
          command:
          - /bin/sh
          - -c            
          env:
          - name: ROOT
            value: /usr/local/nvidia
          - name: NVIDIA_CONTAINER_RUNTIME_MODES_CDI_DEFAULT_KIND
            value: management.nvidia.com/gpu
          - name: NVIDIA_VISIBLE_DEVICES
            value: void
          - name: TOOLKIT_PID_FILE
            value: /run/nvidia/toolkit/toolkit.pid
          - name: NRI_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: CDI_ENABLED
            value: "true"
          - name: NVIDIA_RUNTIME_SET_AS_DEFAULT
            value: "false"
          - name: NVIDIA_CONTAINER_RUNTIME_MODE
            value: cdi
          - name: CRIO_CONFIG_MODE
            value: config
          - name: CONTAINERD_SOCKET
            value: /runtime/sock-dir/containerd.sock
          - name: RUNTIME
            value: containerd
          - name: CONTAINERD_RUNTIME_CLASS
            value: nvidia
          - name: RUNTIME_CONFIG
            value: /runtime/config-dir/config.toml
          - name: CONTAINERD_CONFIG
            value: /runtime/config-dir/config.toml
          - name: RUNTIME_DROP_IN_CONFIG
            value: /runtime/config-dir.d/99-nvidia.toml
          - name: RUNTIME_DROP_IN_CONFIG_HOST_PATH
            value: /etc/containerd/conf.d/99-nvidia.toml
          - name: RUNTIME_SOCKET
            value: /runtime/sock-dir/containerd.sock                                
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: nvcr.io/nvidia/k8s/container-toolkit:v1.19.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /bin/entrypoint.sh
            name: nvidia-container-toolkit-entrypoint
            readOnly: true
            subPath: entrypoint.sh
          - mountPath: /run/nvidia
            name: run-nvidia
          - mountPath: /usr/local/nvidia
            name: toolkit-install-dir
          - mountPath: /usr/share/containers/oci/hooks.d
            name: crio-hooks
          - mountPath: /host
            mountPropagation: HostToContainer
            name: host-root
            readOnly: true
          - mountPath: /var/run/cdi
            name: cdi-root
          - mountPath: /runtime/config-dir/
            name: containerd-config
          - mountPath: /runtime/config-dir.d/
            name: containerd-drop-in-config
          - mountPath: /runtime/sock-dir/
            name: containerd-socket      
          resources:
            {{- toYaml .Values.resources | nindent 12 }}      
        - name: nvidia-driver-ctr
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: "DRIVER_LOCATION"
            value: "{{ .Values.driverLocation }}"                                
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: var-log
              mountPath: /var/log
            - name: dev-log
              mountPath: /dev/log
            - name: host-os-release
              mountPath: "/host-etc/os-release"
              readOnly: true
            - name: host-sys
              mountPath: /sys
            - name: lib-firmware
              mountPath: /lib/firmware
            - mountPath: /run/mellanox/drivers/usr/src
              mountPropagation: HostToContainer
              name: mlnx-ofed-usr-src
            - mountPath: /run/mellanox/drivers
              mountPropagation: HostToContainer
              name: run-mellanox-drivers
            - mountPath: /run/nvidia
              mountPropagation: Bidirectional
              name: run-nvidia
            - mountPath: /run/nvidia-fabricmanager
              name: run-nvidia-fabricmanager
            - mountPath: /run/nvidia-topologyd
              name: run-nvidia-topologyd             
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            defaultMode: 448
            name: nvidia-container-toolkit-entrypoint
          name: nvidia-container-toolkit-entrypoint      
        - name: var-log
          hostPath:
            path: /var/log
        - name: dev-log
          hostPath:
            path: /dev/log
        - name: host-os-release
          hostPath:
            path: "/etc/os-release"
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: lib-firmware
          hostPath:
            path: /lib/firmware
            type: Directory
        - hostPath:
            path: /run/nvidia
            type: DirectoryOrCreate
          name: run-nvidia
        - hostPath:
            path: /run/nvidia-fabricmanager
            type: DirectoryOrCreate
          name: run-nvidia-fabricmanager
        - hostPath:
            path: /run/nvidia-topologyd
            type: DirectoryOrCreate
          name: run-nvidia-topologyd
        - hostPath:
            path: /run/mellanox/drivers/usr/src
            type: DirectoryOrCreate
          name: mlnx-ofed-usr-src
        - hostPath:
            path: /run/mellanox/drivers
            type: DirectoryOrCreate
          name: run-mellanox-drivers
        - hostPath:
            path: /usr/local/nvidia
            type: ""
          name: toolkit-install-dir
        - hostPath:
            path: /run/containers/oci/hooks.d
            type: ""
          name: crio-hooks
        - hostPath:
            path: /dev/char
            type: ""
          name: host-dev-char
        - hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
          name: cdi-root
        - hostPath:
            path: /etc/containerd
            type: DirectoryOrCreate
          name: containerd-config
        - hostPath:
            path: /run/k3s/containerd
            type: ""
          name: containerd-socket
        - hostPath:
            path: /
            type: ""
          name: host-root
        - hostPath:
            path: /etc/containerd/conf.d
            type: DirectoryOrCreate
          name: containerd-drop-in-config                    